name: Test Deployment

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/**'
      - 'scripts/**'

jobs:
  test-docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: task-calendar-manager:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker Compose
      run: |
        docker-compose config
        docker-compose up -d
        sleep 30
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Cleanup
        docker-compose down

  test-scripts:
    name: Test Deployment Scripts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test script syntax
      run: |
        bash -n scripts/deploy.sh
        bash -n scripts/setup-server.sh
        
    - name: Test script permissions
      run: |
        chmod +x scripts/deploy.sh scripts/setup-server.sh
        ls -la scripts/

  test-nginx-config:
    name: Test Nginx Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install nginx
      run: sudo apt-get update && sudo apt-get install -y nginx

    - name: Test nginx configuration
      run: |
        sudo nginx -t -c $(pwd)/nginx.conf